name: RTC Tracker ApiDocs Run

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      RTC_APIDOCS_TOKEN:  ${{ secrets.RTC_APIDOCS_TOKEN }}
      RTC_APIDOCS_USER:  ${{ secrets.RTC_APIDOCS_USER }}
    steps:
      - name:  Fetch RCT-Tracker-ApiDocs-Linux.zip
        run:   curl -L -s -o "#1" https://github.com/Roblox-Tracking-Central-Backend/API-Docs/releases/latest/download/{RTC-Tracker-ApiDocs-Linux.zip}
        shell: bash

      - name:  Extract RTC-Tracker-ApiDocs-Linux.zip
        run:   7z x RTC-Tracker-ApiDocs-Linux.zip
        shell: bash
        
      - name:  Modify RobloxTrackingCentral.Trackers.Api.Docs Permissions
        run:   chmod +x ./RobloxTrackingCentral.Trackers.Api.Docs
        shell: bash
        
      - name:  Run RobloxTrackingCentral.Trackers.Api.Docs
        run:   ./RobloxTrackingCentral.Trackers.Api.Docs
        shell: bash